### PR TITLE
Updated the patch file with a slight modification for FreeBSD and Nginx Version # Support

### PR DESCRIPTION
**Pull request by adalan**
I've installed this patch on 4 different boxes using Nginx 1.0.12 with success. I have to make a slight modification to get this to install via the ports tree.

### CODE REVIEW

**Comment by yaoweibin** [comment]
Do you just change the patch pathing? I can't find any other differences 
with the 1.0.6 patch.

It seems I can apply the 1.0.6 patch in my FreeBSD box directly. It 
can't work with the ports?

**Comment by adalan** [comment]
All that was changed is the file path. Are you compiling from source when you apply the patch? When I include this file via the ports Makefile, without making the patch pathing, I get prompted for which files to patch. If I change the path, the file is patched without any intervention.

I can throw a doc up what changes I'm making to the Makefile as well as the location of the patch file if that helps make things clear.

**Comment by yaoweibin** [comment]
Yes, I just apply the patch in the source code, not the ports Makefile. 
It compiles OK.

You can show me you docs.

**Comment by adalan** [comment]
In the current setup, I've been hijacking the existing syslog patch following this:

   put your patch file here: 

```
/usr/ports/www/nginx/files/extra-patch-syslog_support
```

   edit /usr/ports/www/nginx/Makefile:
      line 610: replace existing syslog definition with the following -

```
.if defined(WITH_SYSLOG_SUPPORT)
CONFIGURE_ARGS+=--add-module=/usr/home/csnuser/nginx_syslog_patch
EXTRA_PATCHES+= ${PATCHDIR}/extra-patch-syslog_support
.endif  
```

I then extract your module to 

```
 /usr/home/csnuser/nginx_syslog_patch
```

I plan on making an update to the actual nginx port to support your patch / module, but that won't happen until after I've completed testing. Let me know if this is clear.

**Comment by yaoweibin** [comment]
OK, If there is any problem in the testing, tell me. Thanks.

**Comment by adalan** [comment]
The only issue I've I had is the patch path (which is what this pull request is for)

**Pull request merged**
